/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyBanner {
        "messages": string[];
        "slideTime": number;
    }
}
declare global {
    interface HTMLMyBannerElement extends Components.MyBanner, HTMLStencilElement {
    }
    var HTMLMyBannerElement: {
        prototype: HTMLMyBannerElement;
        new (): HTMLMyBannerElement;
    };
    interface HTMLElementTagNameMap {
        "my-banner": HTMLMyBannerElement;
    }
}
declare namespace LocalJSX {
    interface MyBanner {
        "messages"?: string[];
        "slideTime"?: number;
    }
    interface IntrinsicElements {
        "my-banner": MyBanner;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-banner": LocalJSX.MyBanner & JSXBase.HTMLAttributes<HTMLMyBannerElement>;
        }
    }
}
